# Generated by Django 4.2.7 on 2025-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('technology', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Vue', 'Vue'), ('PostgreSQL', 'PostgreSQL'), ('Docker', 'Docker')], max_length=20, verbose_name='Технология')),
                ('image', models.ImageField(blank=True, upload_to='project_images/', verbose_name='Изображение')),
                ('project_link', models.URLField(blank=True, verbose_name='Ссылка на проект')),
                ('github_link', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('star_count', models.IntegerField(default=0, verbose_name='Звёзды на GitHub')),
                ('fork_count', models.IntegerField(default=0, verbose_name='Форки на GitHub')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_on'],
            },
        ),
    ]
